### ISSUE TITLE
Add instructions to README for running locally

### ISSUE THREAD

**Issue by filoxo** [filoxo/solid-state-react#1]
Add very brief instructions on how to run this project locally. See my [shakespeare-ratings](https://github.com/filoxo/shakespeare-ratings) repo for an example.

**Comment by ninariccimarie** [comment]
hello @filoxo may I also take on this task 🙏

**Comment by filoxo** [comment]
Sounds good @ninariccimarie, please let me know if you need any additional info.

**Comment by ninariccimarie** [comment]
@filoxo I found that I'll only need to clone then do `yarn start`
do you plan on having any other steps, like the one you've linked above? so I may include those steps on the README

**Comment by filoxo** [comment]
Yes that is pretty much all that is needed (in addition to `yarn install`). Just needs to be added to the readme using markdown syntax.
