### ISSUE TITLE
Upgrade dependencies 

### ISSUE THREAD

**Issue by filoxo** [filoxo/solid-state-react#10]
GitHub is displaying a banner that there are insecure dependencies. After #8 is done, I'd like to upgrade everything else as well. This should be done with `yarn upgrade-interactive`.

**Comment by jenniferkaplannyc** [comment]
I can do this.

**Comment by jenniferkaplannyc** [comment]
Let me know when #8 is done.

**Comment by filoxo** [comment]
Hi @jenniferkaplannyc, this was resolved in #11 in one go. Thanks for your willingness to help!
