### ISSUE TITLE
Refactor Menu component to use react-modal instead of react-portal-minimal

### ISSUE THREAD

**Issue by filoxo** [filoxo/solid-state-react#15]
Refactor Menu component to use [react-modal](https://github.com/reactjs/react-modal) instead of react-portal-minimal.

**Comment by WebDevRaj** [comment]
I'll give a try on this.

**Comment by filoxo** [comment]
Sounds good, let me know if you have any questions or problems. Thanks!

**Comment by filoxo** [comment]
Resolved in #19
