### ISSUE TITLE
Add testing for components

### ISSUE THREAD

**Issue by filoxo** [filoxo/solid-state-react#3]
I'd like to begin testing the components using [react-testing-library](https://github.com/kentcdodds/react-testing-library) instead of ~~Jest~~ Enzyme. This work might be dependent on #2 first though.

**Comment by filoxo** [comment]
I'd only like to focus on getting react-testing-library installed, set up, and maybe a few simple tests; nothing too fancy.

**Comment by filoxo** [comment]
If anyone feels intimidated by testing or would want some guidance please feel free to reach out! I'd be happy to team up, or pair program to figure this out together. 🚧

**Comment by filoxo** [comment]
I began some work in #17, but I'm sure there's more that can be done! Leaving this issue open in case anyone wants to learn/implement unit testing for React components.

**Comment by filoxo** [comment]
@karenkgs much appreciated! You're correct, just find a component that could use some testing. Spotlight and Section are really simple, Menu will be trickier. Please let me know if you have any questions!

**Comment by karenkgs** [comment]
Hi @filoxo, can you take a look at my PR: https://github.com/filoxo/solid-state-react/pull/21 to see if I'm in the right direction?

Thank you! 😃
