### ISSUE TITLE
Add prettier

### ISSUE THREAD

**Issue by filoxo** [filoxo/solid-state-react#4]
I'm a big fan of [prettier] and would like to add it to this project. There are two parts to this work: 
1. Install prettier and execute as a precommit hook using husky
    - [Installing prettier as precommit hook instructions](https://prettier.io/docs/en/precommit.html#option-1-lint-staged-https-githubcom-okonet-lint-staged)
2. Format existing files

Please use the same formatting options as in this commit: https://github.com/filoxo/kgb-scrape-challenge/commit/e2002abd56c7286e679fb91331ae2a106d9e927d 
These instructions are probably a good guide for how I'd like this completed.

**Comment by ninariccimarie** [comment]
hello @filoxo I'd like to take on this issue

**Comment by filoxo** [comment]
Sounds good @ninariccimarie, please let me know if you need any additional info.
